### ISSUE TITLE
jx-requirements.yaml output for devEnvApprovers is malformed

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/terraform-google-jx#45]
After successfully creating a cluster as per Readme, the resulting jx-requirements.yaml file does not have a properly formed empty value for devEnvApprovers.

```
cluster:
  clusterName: "dks-cjxd8-terra"
  devEnvApprovers: 

  environmentGitOwner: ""
  project: "apps-dev-229310"
  provider: gke
  zone: "us-central1-a"
```
